server:
  port: 80
spring:
  datasource:
    url: jdbc:sqlite:/data.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  thymeleaf:
    prefix: file:templates/
mybatis:
  mapper-locations: classpath:mapper/*.xml